---
- name: Disable password complexity check on Server core
  hosts: shdc
  gather_facts: no
  tasks:
    - name: PS code to modify secpol
      win_shell: |
        secedit /export /cfg c:\secpol.cfg
        (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
        secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
        rm -force c:\secpol.cfg -confirm:$false