- hosts: siteA
  gather_facts: yes
  tasks:
  - win_domain_membership:
      dns_domain_name: shdom.com
      hostname: Ansibleclient1
      domain_admin_user: shdomadmin@shdom.com
      domain_admin_password: shdomadmin1
      domain_ou_path: "OU=Windows,OU=Servers,DC=shdom,DC=com"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
    msg: "Reboot initiated by Ansible"
     connect_timeout: 5
     reboot_timeout: 100
     pre_reboot_delay: 0
     post_reboot_delay: 10
     test_command: whoami