---
- name: join host to domain
  hosts: siteA
  tasks:
   - name: set DNS IP to Network interface
     win_shell: |
       $getIndex = Get-NetAdapter | Select-Object InterfaceIndex
       set-DnsClientServerAddress -InterfaceIndex $getIndex.InterfaceIndex -ServerAddresses ("192.168.56.105")
       
   - name: Disable firewall policies and set Time Zone to IST
     win_shell: |
       Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False 
       Set-TimeZone -Id "India Standard Time" -PassThru

   - name: Joining host Ansibleclient to domain
     win_domain_membership:
      dns_domain_name: shdom
      hostname: Ansibleclient
      domain_admin_user: shdomadmin@shdom
      domain_admin_password: shdomadmin1
      #domain_ou_path: "OU=Windows,OU=Servers,DC=shdom,DC=com"
      state: domain
     register: domain_state

   - win_reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 100
      pre_reboot_delay: 0
      post_reboot_delay: 10
      test_command: whoami
     when: domain_state.reboot_required
   
  
