- name: Reboot host and wait for it to restart
  hosts: shdc
  gather_facts: no
  tasks:
  - win_reboot:
     msg: "Reboot initiated by Ansible"
     connect_timeout: 5
     reboot_timeout: 100
     pre_reboot_delay: 0
     post_reboot_delay: 10
     test_command: whoami