---
- name: Change host name
  gather_facts: yes
  hosts: shdc
  
  tasks:
    - name: Change the hostname to shdomdc
      win_hostname:
        name: shdomdc
      register: res

    - name: Reboot
      win_reboot:
      when: res.reboot_required

  #  - name: Validate that the netlogon service has started, before running the next task
  #    ansible.windows.win_reboot:
  #      test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'


