---
- name: test calling PS1
  gather_facts: no
  hosts: all
  vars:
   - MaxEvents: 10
   - LogName: "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational"
   - searchstring: "ClientAdmin"
  tasks:
   - name: Execute the PS script
     script: Read-eventlogsParams.ps1 -LogName {{ LogName }} -MaxEvents {{ MaxEvents }} -searchstring {{ searchstring }}
     register: outps

   - debug:
       msg: "{{ outps.stdout }}"